language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
    
before_script:
     - chmod +x grailsw
     - chmod +x test-project/grailsw
     - ./grailsw refresh-dependencies
     - cd test-project
     - grailsw refresh-dependencies
     - grailsw war
     - cd ..
     
script: 
  ./grailsw "test-app -integration"