language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
    
before_script:
     - chmod +x grailsw
     - chmod +x test-project/grailsw
     
script: ./grailsw refresh-dependencies
  && ./test-project/grailsw refresh-dependencies
  && ./test-project/grailsw war
  && ./grailsw "test-app -integration"